Translucent panel
BHoM/IES_Toolkit pull request #186
Opened 2022-01-27 15:39 UTC by robinflyman

Closes # 182

2022-01-27 16:50 UTC, FraserGreenroyd requested changes

2022-01-27 16:50 UTC, FraserGreenroyd commented on IES_Engine/Convert/Environment/Panel.cs
> +                bool isTranslucent = panels[x].Type != PanelType.Shade;
Put this before the for loop and set it as `panels.First().Type` instead of `panels[x].Type`

2022-01-30 09:47 UTC, FraserGreenroyd requested changes

2022-01-30 09:47 UTC, FraserGreenroyd commented on IES_Adapter/CRUD/Read.cs
> +                    panels.Add(space.FromIESShading(_settingsIES,panelType)); //Make a shade panel
```suggestion
                    panels.Add(space.FromIESShading(_settingsIES, panelType)); //Make a shade panel
```

2022-01-30 09:47 UTC, FraserGreenroyd commented on IES_Engine/Convert/Environment/Panel.cs
> +        public static Panel FromIESShading(this List<string> iesPanel, SettingsIES settingsIES, PanelType panelType)
Update `line 137` to utilise this `PanelType` input

2022-02-07 15:31 UTC, RMildiner approved these changes
Tested the GEM file creation using a GH script and then imported the GEM into IES. The translucent shade component appeared in the correct place and was recognised as translucent by IES straight away. Seems to work.

2022-02-07 15:57 UTC, jamesramsden-bh requested changes
Pushing to IES: Pass. Confirmed with @RMildiner that a pushed model opens in IES correctly.

Pulling to IES: Fail. The 'opening' within the shade is offset by a vector of approximately 8m,8m,8m. This issue is not evident when using a non-translucent shade. (Test GEM files for translucent and non-translucent within the zip file attached.) 
[translucent push and pull tests.zip](https://github.com/BHoM/IES_Toolkit/files/8016726/translucent.push.and.pull.tests.zip)

2022-02-09 16:06 UTC, jamesramsden-bh commented
Fail from previous comment now fixed. @FraserGreenroyd now ready for review. 
@robinflyman no action needed from you right now.

2022-02-11 16:25 UTC, FraserGreenroyd requested changes
The use of the newer C# tuples, though very nice, isn't quite in line with the rest of the BHoM. As such, it'd be better to stick with the `Output<t1, tn>` solutions previously implemented.

However, I think we might want to update `FilterPanelsByType` method in the Environment_Engine, and allow it to take in a multiple params of types to filter but also group. I'll raise an issue for that to be tackled as part of this work but before this can be merged.

Then we can rectify this PR to be more in line with what's expected 😄

2022-02-15 10:20 UTC, FraserGreenroyd requested changes

2022-02-15 10:20 UTC, FraserGreenroyd commented on IES_Engine/Convert/Environment/Panel.cs
> +                //This if-statement is a slightly hacky fix for the IES implementation of translucent shades,
```suggestion
                //This if-statement is a fix for the IES implementation of translucent shades, 
```

2022-02-15 10:30 UTC, FraserGreenroyd commented
@BHoMBot check core

2022-02-15 10:33 UTC, FraserGreenroyd requested changes

2022-02-15 10:33 UTC, FraserGreenroyd commented on IES_Engine/Convert/Environment/Panel.cs
> +        public static Panel FromIESShading(this List<string> iesPanel, SettingsIES settingsIES, PanelType panelType)
```suggestion
        [PreviousVersion("5.1", "BH.Engine.Adapters.IES.Convert.FromIESShading(System.Collections.Generic.List<System.String>, BH.oM.IES.Settings.SettingsIES)")]
        public static Panel FromIESShading(this List<string> iesPanel, SettingsIES settingsIES, PanelType panelType)
```

2022-02-15 10:33 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2022-02-15 10:46 UTC, jamesramsden-bh approved these changes
Tested against translucent shading sections of testing procedure, LGTM.

2022-02-15 10:48 UTC, FraserGreenroyd commented
@BHoMBot check installer

2022-02-15 11:30 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-02-15 12:24 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2022-02-15 12:25 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5199266217

2022-02-15 12:25 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5199267343

2022-02-15 12:27 UTC, FraserGreenroyd approved these changes
Tested through on test procedure by others, code reviewed by me, updates required to engine have been implemented and are working happily. Versioning and installer checks are happy, so deploying to alpha for further testing.

2022-02-15 12:31 UTC, merged