Add SurfaceID fragment
BHoM/IES_Toolkit pull request #198
Opened 2022-10-25 10:54 UTC by kprusicka

### Issues addressed by this PR
Fixes #197 

 ### Test files

 ### Changelog

 ### Additional comments

2022-10-25 14:03 UTC, kprusicka commented
@BHoMBot check compliance

2022-10-25 14:05 UTC, FraserGreenroyd requested changes
Please address the compliance issues too

2022-10-25 14:05 UTC, FraserGreenroyd commented on IES_oM/Fragments/SurfaceIndexFragment.cs
> +        public virtual int SurfaceID { get; set; } = -1;
Please add a description for the property with an example usage

2022-10-25 15:18 UTC, FraserGreenroyd commented
@BHoMBot fix copyright headers ref. 9094972189

2022-10-25 15:18 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 9094960875

2022-10-25 16:40 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-10-27 09:30 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-10-27 10:27 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-10-28 09:15 UTC, FraserGreenroyd approved these changes
Changes made, all looks good to me, great work @kprusicka

2022-10-28 09:15 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-10-28 09:16 UTC, merged